version: '3.1'

services:

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
