version: '3.3'

services:
  postgresql:
    container_name: postgresql
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpassword}
      ### Extensions ###
      INSTALL_PLRUST: ${INSTALL_PLRUST:-false}
      INSTALL_CRON: ${INSTALL_CRON:-false}
      INSTALL_HTTP: ${INSTALL_HTTP:-false}
      INSTALL_JWT: ${INSTALL_JWT:-false}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    shm_size: 512mb
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  pg_data: {}
  pg_logs: {}
