version: '3.1'

services:

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: PxH2Z5zY35FFfXVu
      logging_collector: "on"
      log_destination: "stderr"
      log_statement: "all"
    ports:
      - 49152:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  pg_data: {}
  pg_logs: {}
